alias g="git"
__git_complete g __git_main
alias gal="git config --list | grep alias"
alias gp="git pull"
alias gs="git status"
alias gb="git branch"
alias gl="git log --graph --decorate --pretty=format:'%C(auto)%h%d %s (%cr)' --abbrev-commit --all"
alias glg="git log --graph --decorate --pretty=oneline --abbrev-commit --all"
alias gc="git clone"
alias gd="git diff"
alias gdd="git diff origin/dev"
alias gdm="git diff origin/main"
alias gdvd="git diff origin/v5-dev"
alias grh="git reset HEAD --hard"
